const { test } = require('tap');

const LRUSet = require('../lib/lru_set');

test('LRUSet', suite => {

  suite.test('should allow max total length items', t => {
    var lru = new LRUSet(16);
    t.type(lru, LRUSet);
    t.strictSame(Array.from(lru), []);
    t.strictEquals(lru.size, 0);
    t.strictEquals(lru.length, 0);
    t.strictEquals(lru.maxLength, 16);
    t.strictEquals(lru.has(""), false);
    lru.add("");
    t.strictEquals(lru.size, 1);
    t.strictEquals(lru.length, 4);
    t.strictSame(Array.from(lru), [""]);
    t.strictEquals(lru.has(""), true);
    t.strictEquals(lru.has("foo"), false);
    lru.add("foo");
    t.strictEquals(lru.size, 2);
    t.strictEquals(lru.length, 11);
    t.strictSame(Array.from(lru), ["","foo"]);
    lru.add("foo");
    t.strictEquals(lru.size, 2);
    t.strictEquals(lru.length, 11);
    t.strictSame(Array.from(lru), ["","foo"]);
    t.strictEquals(lru.has("foo"), true);
    t.strictSame(Array.from(lru), ["","foo"]);
    t.strictEquals(lru.has(""), true);
    t.strictSame(Array.from(lru), ["foo",""]);
    lru.add("A");
    t.strictEquals(lru.size, 3);
    t.strictEquals(lru.length, 16);
    t.strictSame(Array.from(lru), ["foo","","A"]);
    t.strictEquals(lru.has("foo"), true);
    t.strictSame(Array.from(lru), ["","A","foo"]);
    t.strictEquals(lru.has(""), true);
    t.strictSame(Array.from(lru), ["A","foo",""]);
    t.strictEquals(lru.has("A"), true);
    t.strictSame(Array.from(lru), ["foo","","A"]);
    t.strictEquals(lru.has(""), true);
    t.strictSame(Array.from(lru), ["foo","A",""]);
    lru.add("12345678");
    t.strictEquals(lru.size, 2);
    t.strictEquals(lru.length, 16);
    t.strictSame(Array.from(lru), ["","12345678"]);
    t.strictEquals(lru.has("foo"), false);
    t.strictEquals(lru.has(""), true);
    t.strictSame(Array.from(lru), ["12345678",""]);
    t.strictEquals(lru.has("12345678"), true);
    t.strictSame(Array.from(lru), ["","12345678"]);
    lru.add("1234567890");
    t.strictEquals(lru.size, 1);
    t.strictEquals(lru.length, 14);
    t.strictSame(Array.from(lru), ["1234567890"]);
    t.strictEquals(lru.has("foo"), false);
    t.strictEquals(lru.has(""), false);
    t.strictEquals(lru.has("12345678"), false);
    t.strictEquals(lru.has("1234567890"), true);
    t.strictSame(Array.from(lru), ["1234567890"]);
    lru.add("bar");
    t.strictEquals(lru.size, 1);
    t.strictEquals(lru.length, 7);
    t.strictSame(Array.from(lru), ["bar"]);
    t.strictEquals(lru.has("foo"), false);
    t.strictEquals(lru.has(""), false);
    t.strictEquals(lru.has("12345678"), false);
    t.strictEquals(lru.has("1234567890"), false);
    t.strictEquals(lru.has("bar"), true);
    lru.add("baz");
    t.strictEquals(lru.size, 2);
    t.strictEquals(lru.length, 14);
    t.strictSame(Array.from(lru), ["bar","baz"]);
    t.strictEquals(lru.has("foo"), false);
    t.strictEquals(lru.has(""), false);
    t.strictEquals(lru.has("12345678"), false);
    t.strictEquals(lru.has("1234567890"), false);
    t.strictEquals(lru.has("bar"), true);
    t.strictSame(Array.from(lru), ["baz","bar"]);
    t.strictEquals(lru.has("baz"), true);
    t.strictSame(Array.from(lru), ["bar","baz"]);
    lru.add("foooo");
    t.strictEquals(lru.size, 2);
    t.strictEquals(lru.length, 16);
    t.strictSame(Array.from(lru), ["baz","foooo"]);
    t.strictEquals(lru.has("foo"), false);
    t.strictEquals(lru.has(""), false);
    t.strictEquals(lru.has("12345678"), false);
    t.strictEquals(lru.has("1234567890"), false);
    t.strictEquals(lru.has("bar"), false);
    t.strictEquals(lru.has("baz"), true);
    t.strictSame(Array.from(lru), ["foooo","baz"]);
    t.strictEquals(lru.has("foooo"), true);
    t.strictSame(Array.from(lru), ["baz","foooo"]);
    lru.delete("foooo");
    t.strictEquals(lru.size, 1);
    t.strictEquals(lru.length, 7);
    t.strictSame(Array.from(lru), ["baz"]);
    t.strictEquals(lru.has("foooo"), false);
    t.strictEquals(lru.has("bar"), false);
    t.strictEquals(lru.has("baz"), true);
    t.strictSame(Array.from(lru), ["baz"]);
    lru.clear();
    t.strictEquals(lru.size, 0);
    t.strictEquals(lru.length, 0);
    t.end();
  });

  suite.end();
});
